drop table t_ordenes if exists;
drop table t_users if exists;
drop table t_items if exists;
create table t_users (
    user_nom varchar(255) not null unique, 
    user_prop integer,
    primary key (user_nom));
create table t_items (
    item_nom varchar(255) not null unique, 
    item_prop integer, 
    item_tipo varchar(255), 
    primary key (item_nom));
create table t_ordenes (
    ord_id bigint generated by default as identity 
    (start with 3L increment by 1),
    ord_user varchar(255),
    ord_item varchar(255),
    primary key (ord_id));
alter table t_ordenes 
    add constraint orden_item_fk 
    foreign key (ord_item) references t_items;
alter table t_ordenes 
    add constraint orden_user_fk 
    foreign key (ord_user) references t_users
        ON DELETE CASCADE;
insert into 
    t_users (user_nom, user_prop)
    values 
        ('Guybrush', 15),
        ('Bernard Bernoulli', 100),
        ('Arthur', 200),
        ('Nick and Tom', 250),
        ('Donatello', 300);
insert into 
    t_items (item_nom, item_prop, item_tipo)
    values
        ('Ghosts n Goblins', 20, 'RetroGame'),
        ('El dia del tentaculo', 7, 'RetroGame'),
        ('Teenage Mutant Ninja Turtles II', 100, 'RetroGame' );
insert into 
    t_ordenes (ord_id, ord_user, ord_item) 
    values 
        (1L, 'Guybrush', 'El dia del tentaculo'),
        (2L, 'Donatello', 'Teenage Mutant Ninja Turtles II');
